#include "..\far-sdk\farversion.hpp"

#define PLUGIN_BUILD 1
#define PLUGIN_DESC L"xTRD Plugin for Far Manager 3"
#define PLUGIN_NAME L"xTRD"
#define PLUGIN_FILENAME L"xTRD.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
